# Don't print a new line at the start of the prompt
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
#success_symbol = "[\$](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✕ ](bold red) "
vicmd_symbol = "[V](bold green) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[username]
style_user = "#d7005f"
format = "[\\[$user\\]]($style) "
disabled = false
show_always = true

[directory]
style = "bold #d75f00"

[jobs]
style = "#d7d7ff"

[git_branch]
style = "#af00d7"

[cmd_duration]
style = "#d7ff00"
